export const Stocks = [
  {
    warehouse: "Electrodomésticos",
    id: 'almacen-1',
    items: [
      {
        id: crypto.randomUUID(),
        name: "TV 58'' Samsung",
        image: 'https://images.samsung.com/is/image/samsung/es-uhdtv-mu6125-ue58mu6125kxxc-frontblack-80708680?$Q90_1248_936_F_PNG$',
        description: 'Televisor 4K UHD',
        quantity: 12,
        purchase_price: 400,
        sales_price: 650,
      },
      {
        id: crypto.randomUUID(),
        name: "Lavadora LG 9kg",
        image: 'https://expertclima.es/7162-large_default/lavadora-lg-f4j7vy2wd-9-kg-1400-rpm-wifi.jpg',
        description: 'Carga frontal',
        quantity: 8,
        purchase_price: 300,
        sales_price: 520,
      },
      {
        id: crypto.randomUUID(),
        name: "Microondas Panasonic",
        image: 'https://i.ytimg.com/vi/59MPJIVmIv8/maxresdefault.jpg',
        description: '20L digital',
        quantity: 20,
        purchase_price: 60,
        sales_price: 110,
      },
      {
        id: crypto.randomUUID(),
        name: "Refrigerador Bosch",
        image: 'https://cdn.grupoelcorteingles.es/SGFM/dctm/MEDIA03/202404/02/00104721764175____1__1200x1200.jpg',
        description: 'No Frost',
        quantity: 5,
        purchase_price: 700,
        sales_price: 1100,
      },
      {
        id: crypto.randomUUID(),
        name: "Aspiradora Dyson",
        image: 'https://dyson-h.assetsadobe2.com/is/image/content/dam/dyson/images/products/primary/479333-01.png',
        description: 'Sin cable',
        quantity: 10,
        purchase_price: 250,
        sales_price: 450,
      },
    ],
  },
  {
    warehouse: "Tecnología",
    id:'almacen-2',
    items: [
      {
        id: crypto.randomUUID(),
        name: "Laptop Dell XPS 13",
        image: 'https://m.media-amazon.com/images/I/91MXLpouhoL._AC_UF894,1000_QL80_.jpg',
        description: 'Intel i7, 16GB RAM',
        quantity: 6,
        purchase_price: 900,
        sales_price: 1400,
      },
      {
        id: crypto.randomUUID(),
        name: "iPhone 14",
        image: 'https://m.media-amazon.com/images/I/71yzJoE7WlL._AC_UF1000,1000_QL80_.jpg',
        description: '128GB',
        quantity: 15,
        purchase_price: 700,
        sales_price: 1000,
      },
      {
        id: crypto.randomUUID(),
        name: "Tablet iPad Air",
        image: 'https://macnificos.com/cdn/shop/files/Apple-iPad-Air-rossellimac-productos-macnificos.jpg?v=1746530328',
        description: '64GB WiFi',
        quantity: 10,
        purchase_price: 500,
        sales_price: 750,
      },
      {
        id: crypto.randomUUID(),
        name: "Monitor LG 27''",
        image: 'https://canarias.worten.es/i/91810c2aabe6136d77cea6e849a8a96d4d083566',
        description: 'Full HD IPS',
        quantity: 18,
        purchase_price: 150,
        sales_price: 280,
      },
      {
        id: crypto.randomUUID(),
        name: "Teclado Mecánico Logitech",
        image: 'https://img.pccomponentes.com/articles/1001/10012182/1219-logitech-g-pro-teclado-mecanico-tkl-gaming-rgb-switch-gx-blue-con-clic-perceptible-5e485cec-f514-493f-9d30-1decf0589998.jpg',
        description: 'RGB',
        quantity: 25,
        purchase_price: 70,
        sales_price: 130,
      },
    ],
  },
  {
    warehouse: "Hogar",
    id: 'almacen-3',
    items: [
      {
        id: crypto.randomUUID(),
        name: "Sofá 3 plazas",
        image: 'https://mubak.com/3837-large_default/sofa-3-plazas-de-198-cm.jpg',
        description: 'Tela gris',
        quantity: 4,
        purchase_price: 350,
        sales_price: 700,
      },
      {
        id: crypto.randomUUID(),
        name: "Mesa de comedor",
        image: 'https://www.idmarket.com/43558-product_main_2x/detroit-mesa-de-comedor-rectangular-extensible-8-12-personas-200-250-cm.jpg',
        description: 'Madera maciza',
        quantity: 7,
        purchase_price: 200,
        sales_price: 450,
      },
      {
        id: crypto.randomUUID(),
        name: "Silla ergonómica",
        image: 'https://www.ofisillas.es/images/product/1/large/pl_1_1_6066.jpg',
        description: 'Oficina',
        quantity: 14,
        purchase_price: 80,
        sales_price: 160,
      },
      {
        id: crypto.randomUUID(),
        name: "Lámpara LED",
        image: 'https://kosiluz.es/23684-large_default/lampara-de-interior-negra-rectangular-led-regulable-otso.jpg',
        description: 'Luz cálida',
        quantity: 30,
        purchase_price: 15,
        sales_price: 35,
      },
      {
        id: crypto.randomUUID(),
        name: "Alfombra decorativa",
        image: 'https://pkm.store/cdn/shop/files/S958fee1731bd4bc88c6fc02ca03e156fP.webp?v=1700148353',
        description: '2x3 metros',
        quantity: 9,
        purchase_price: 60,
        sales_price: 120,
      },
    ],
  },
];